version: "3"
services:
  payment:
    container_name: payment-container
    restart: always  
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8002
    volumes:
      - .:/app
    ports:
      - 8002:8002