version: "3"
services:
  inventory:
    container_name: inventory-container
    restart: always
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8001:8000